openai:
  default: gpt-4o
  models:
    - name: GPT-4o
      value: gpt-4o
      pricing:
        input: 2.50 # Price per million tokens for input
        output: 10.0 # Price per million tokens for output
    - name: GPT-4o-mini
      value: gpt-4o-mini
      pricing:
        input: 0.15 # Price per million tokens for input
        output: 0.60 # Price per million tokens for output

ollama:
  default: llama3
  models:
    - name: Llama 3.2
      value: llama3.2
      pricing:
        input: 0.0 # Local models are free
        output: 0.0 # Local models are free

gemini:
  default: gemini-2.0-flash
  models:
    - name: Gemini 2.5 Pro Preview
      value: gemini-2.5-pro-exp-03-25
      pricing:
        input: 1.25 # Price per million tokens for input (<= 200k tokens)
        output: 10.00 # Price per million tokens for output (<= 200k tokens)
    - name: Gemini 2.0 Flash
      value: gemini-2.0-flash
      pricing:
        input: 0.10 # Price per million tokens for input (text/image/video)
        output: 0.40 # Price per million tokens for output
    - name: Gemini 2.0 Flash-Lite
      value: gemini-2.0-flash-lite
      pricing:
        input: 0.075 # Price per million tokens for input
        output: 0.30 # Price per million tokens for output

vertexai:
  default: gemini-2.0-flash
  models:
    - name: Gemini 2.5 Pro Preview
      value: gemini-2.5-pro-exp-03-25
      pricing:
        input: 1.25 # Price per million tokens for input (<= 200k tokens)
        output: 10.00 # Price per million tokens for output (<= 200k tokens)
    - name: Gemini 2.0 Flash
      value: gemini-2.0-flash
      pricing:
        input: 0.10 # Price per million tokens for input (text/image/video)
        output: 0.40 # Price per million tokens for output
    - name: Gemini 2.0 Flash-Lite
      value: gemini-2.0-flash-lite
      pricing:
        input: 0.075 # Price per million tokens for input
        output: 0.30 # Price per million tokens for output
